linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - forbidigo
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-dirs:
    - var
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - funlen
        - lll
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - scopelint
        - gochecknoglobals
        - goerr113

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
          - "!**/test/**/*"
        allow:
          - $gostd
          - github.com
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com
  gosec:
    excludes:
      - G115
